language: elm

before_deploy:
  - cd ./packages/elmegram.js/ && yarn build && cd ../..
  - yarn build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: xkcd-for-that-bot
  on:
    branch:
      - master
      - fix-crash
  skip_cleanup: true